directory: specification/dashboard/Dashboard.Management
commit: 5ef7e9410d6280259dd419bc7d646de1a5d1bbfa
repo: Azure/azure-rest-api-specs
emitterPackageJsonPath: "eng/azure-typespec-http-client-csharp-mgmt-emitter-package.json"
