directory: specification/dashboard/Dashboard.Management
commit: a03d9e3159075f4b5ab9224c1008d541ee792dc5
repo: Azure/azure-rest-api-specs
emitterPackageJsonPath: "eng/azure-typespec-http-client-csharp-mgmt-emitter-package.json"
