omitted_paths:
  - archive/*
  - eng/*
  - tools/*
  - src/*
  - Documentation/*
  - sdk/*mgmt*/*
  - sdk/*/*.Management.*/*
  - samples/*
  - common/Perf/*
  - common/SmokeTests/*
  - common/Stress/*
  - sdk/*/samples/*
  - sdk/*/*/samples/*
  - sdk/*/swagger/*
  - doc/ApiDocGeneration/*
language: net
root_check_enabled: True
required_readme_sections:
  - "Azure .+ client library for .NET"
  - "^Getting started$":
    - Install the [Pp]ackage
    - Prerequisites
    - Authenticate the [Cc]lient
  - ^Key concepts$
  - ^Examples$
  - ^Troubleshooting$
  - ^Next steps$
  - ^Contributing$
known_presence_issues:
  - ['sdk/alertsmanagement/Microsoft.Azure.Management.AlertsManagement','#5499']
  - ['sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query','#5499']
  - ['sdk/batch/Microsoft.Azure.Batch.FileStaging','#5499']
  - ['sdk/batch/Microsoft.Azure.Batch/Tools','#5499']
  - ['sdk/batch/Microsoft.Azure.Batch/Tools','#5499']
  - ['sdk/cognitiveservices/AnomalyDetector','#5499']
  - ['sdk/cognitiveservices/FormRecognizer','#5499']
  - ['sdk/cognitiveservices/Knowledge.QnAMaker','#5499']
  - ['sdk/cognitiveservices/Language.LUIS.Authoring','#5499']
  - ['sdk/cognitiveservices/Language.LUIS.Runtime','#5499']
  - ['sdk/cognitiveservices/Language.SpellCheck','#5499']
  - ['sdk/cognitiveservices/Language.TextAnalytics','#5499']
  - ['sdk/cognitiveservices/Personalizer','#5499']
  - ['sdk/cognitiveservices/Search.BingAutoSuggest','#5499']
  - ['sdk/cognitiveservices/Search.BingCustomImageSearch','#5499']
  - ['sdk/cognitiveservices/Search.BingCustomSearch','#5499']
  - ['sdk/cognitiveservices/Search.BingEntitySearch/','#5499']
  - ['sdk/cognitiveservices/Search.BingImageSearch/','#5499']
  - ['sdk/cognitiveservices/Search.BingLocalSearch/','#5499']
  - ['sdk/cognitiveservices/Search.BingNewsSearch','#5499']
  - ['sdk/cognitiveservices/Search.BingVideoSearch','#5499']
  - ['sdk/cognitiveservices/Search.BingVisualSearch','#5499']
  - ['sdk/cognitiveservices/Search.BingWebSearch','#5499']
  - ['sdk/cognitiveservices/Vision.ComputerVision','#5499']
  - ['sdk/cognitiveservices/Vision.ContentModerator','#5499']
  - ['sdk/cognitiveservices/Vision.CustomVision.Prediction','#5499']
  - ['sdk/cognitiveservices/Vision.CustomVision.Training','#5499']
  - ['sdk/cognitiveservices/Vision.Face','#5499']
  - ['sdk/cognitiveservices/Vision.FormRecognizer','#5499']
  - ['sdk/containerregistry/Microsoft.Azure.ContainerRegistry','#5499']
  - ['sdk/eventgrid/Microsoft.Azure.EventGrid','#5499']
  - ['sdk/eventhub/Microsoft.Azure.EventHubs.Processor','#5499']
  - ['sdk/eventhub/Microsoft.Azure.EventHubs.ServiceFabricProcessor','#5499']
  - ['sdk/graphrbac/Microsoft.Azure.Graph.RBAC','#5499']
  - ['sdk/hdinsight/Microsoft.Azure.HDInsight.Job','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault.Core','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault.Cryptography','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault.Extensions','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault.WebKey','#5499']
  - ["sdk/mediaservices/Microsoft.Azure.Media.LiveVideoAnalytics.Edge", "#5499"]
  - ['sdk/operationalinsights/Microsoft.Azure.OperationalInsights','#5499']
  - ['sdk/search/Microsoft.Azure.Search.Common','#5499']
  - ['sdk/search/Microsoft.Azure.Search.Data','#5499']
  - ['sdk/search/Microsoft.Azure.Search.Service','#5499']
  - ['sdk/search/Microsoft.Azure.Search','#5499']
  - ['sdk/keyvault','#5499']
  - ['sdk/eventhub','#5499']
  - ['sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query/CHANGELOG.md','#5499']
  - ['sdk/batch/Microsoft.Azure.Batch.Conventions.Files/CHANGELOG.md','#5499']
  - ['sdk/batch/Microsoft.Azure.Batch.FileStaging/CHANGELOG.md','#5499']
  - ['sdk/batch/Microsoft.Azure.Batch/Tools/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/AnomalyDetector/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/FormRecognizer/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Knowledge.QnAMaker/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Language.LUIS.Authoring/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Language.LUIS.Runtime/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Language.SpellCheck/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Language.TextAnalytics/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Personalizer/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingAutoSuggest/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingCustomImageSearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingCustomSearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingEntitySearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingImageSearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingLocalSearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingNewsSearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingVideoSearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingVisualSearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Search.BingWebSearch/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/textanalytics/Azure.AI.TextAnalytics/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Vision.ComputerVision/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Vision.ContentModerator/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Vision.CustomVision.Prediction/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Vision.CustomVision.Training/CHANGELOG.md','#5499']
  - ['sdk/cognitiveservices/Vision.Face/CHANGELOG.md','#5499']
  - ['sdk/containerregistry/Microsoft.Azure.ContainerRegistry/CHANGELOG.md','#5499']
  - ['sdk/eventgrid/Microsoft.Azure.EventGrid/CHANGELOG.md','#5499']
  - ['sdk/eventhub/Microsoft.Azure.EventHubs.Processor/CHANGELOG.md','#5499']
  - ['sdk/eventhub/Microsoft.Azure.EventHubs.ServiceFabricProcessor/CHANGELOG.md','#5499']
  - ['sdk/eventhub/Microsoft.Azure.EventHubs/CHANGELOG.md','#5499']
  - ['sdk/graphrbac/Microsoft.Azure.Graph.RBAC/CHANGELOG.md','#5499']
  - ['sdk/hdinsight/Microsoft.Azure.HDInsight.Job/CHANGELOG.md','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault.Core/CHANGELOG.md','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault.Cryptography/CHANGELOG.md','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault.Extensions/CHANGELOG.md','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault.WebKey/CHANGELOG.md','#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault/CHANGELOG.md','#5499']
  - ['sdk/operationalinsights/Microsoft.Azure.OperationalInsights/CHANGELOG.md','#5499']
  - ['sdk/search/Microsoft.Azure.Search.Common/CHANGELOG.md','#5499']
  - ['sdk/search/Microsoft.Azure.Search.Data/CHANGELOG.md','#5499']
  - ['sdk/search/Microsoft.Azure.Search.Service/CHANGELOG.md','#5499']
  - ['sdk/template/Azure.Template/CHANGELOG.md','#5499']
  - ['sdk/attestation/Microsoft.Azure.Attestation','#5499']

known_content_issues:
  - ['README.md','Root readme']
  - ['doc/README.md','Doc readme']
  - ['sdk/anomalydetector/Azure.AI.AnomalyDetector/README.md', '#5499']
  - ['sdk/core/Azure.Core/README.md', '#5499']
  - ['sdk/core/Azure.Core.Experimental/README.md', '#5499']
  - ['sdk/core/Azure.Core.Amqp/README.md', '#5499']
  - ['sdk/core/System.Memory.Data/README.md', '#5499']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault/README.md','#5499']
  - ['sdk/servicebus/Microsoft.Azure.ServiceBus/README.md','#5499']
  - ['sdk/eventhub/Microsoft.Azure.EventHubs/README.md','#5499']
  - ['sdk/eventhub/Azure.Messaging.EventHubs.Shared/README.md','#5499']
  - ['sdk/alertsmanagement/Microsoft.Azure.Management.AlertsManagement/README.md','#5499']
  - ['sdk/appconfiguration/README.md','azure-sdk-tools/issues/42']
  - ['sdk/appconfiguration/Azure.Data.AppConfiguration/tests/Readme.md','#5499']
  - ['sdk/storage/README.md','azure-sdk-tools/issues/42']
  - ['sdk/cognitiveservices/Language.TextAnalytics/src/README.md','#5499']
  - ['sdk/cognitiveservices/Personalizer/src/README.md','#5499']
  - ['sdk/batch/Microsoft.Azure.Batch/README.md','#5499']
  - ['sdk/batch/Microsoft.Azure.Batch.Conventions.Files/README.md','#5499']
  - ['sdk/extensions/README.md','azure-sdk-tools/issues/42']
  - ['sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs/README.md','azure-sdk-tools/issues/404']
  - ['sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Keys/README.md','azure-sdk-tools/issues/404']
  - ['sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/README.md', 'azure-sdk-tools/issues/404']
  - ['sdk/extensions/Microsoft.Azure.WebJobs.Extensions.Clients/README.md','azure-sdk-tools/issues/404']
  - ['sdk/extensions/Microsoft.Extensions.Azure/README.md','#5499']
  - ['sdk/eventgrid/Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents/README.md', '#15423']
  - ['sdk/eventhub/README.md','azure-sdk-tools/issues/42']
  - ['sdk/search/README.md','azure-sdk-tools/issues/42']
  - ['sdk/formrecognizer/Azure.AI.FormRecognizer/README.md','#5499']
  - ['sdk/formrecognizer/Azure.AI.FormRecognizer/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Blobs/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Blobs/perf/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Blobs.Batch/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Blobs.Cryptography/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Common/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Files.DataLake/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Files.DataLake/perf/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Files.Shares/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Files.Shares/perf/README.md','#11492']
  - ['sdk/storage/Azure.Storage.Queues/README.md','#11492']
  - ['sdk/synapse/Microsoft.Azure.Synapse/README.md','#11492']
  - ['sdk/tables/Azure.Data.Tables/readme.md', '#11492']
  - ['sdk/core/Azure.Core.TestFramework/README.md', '#11492']
  - ['sdk/core/Microsoft.Azure.Core.NewtonsoftJson/README.md', '#15423']
  - ['sdk/core/Microsoft.Azure.Core.Spatial/README.md', '#15423']
  - ['sdk/core/Microsoft.Azure.Core.Spatial.NewtonsoftJson/README.md', '#15423']
  - ['sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/README.md', '#15423']

# .net climbs upwards. placing these to prevent assigning readmes to the wrong project
package_indexing_exclusion_list:
  - 'AutoRest-AzureDotNetSDK'
  - 'NetCoreTestPublish'
  - 'ObjectModelCodeGenerator'
  - 'CodeGenerationLibrary'
  - 'ProxyLayerParser'
  - 'IntegrationTestCommon'
  - 'Azure.Template'
  - 'SampleSDKTestPublish'
  - 'CSProjTestPublish'
  - 'ConfigureAwaitAnalyzer'
  - 'Microsoft.WindowsAzure.Build.Tasks'
  - 'Microsoft.Azure.Services.AppAuthentication.TestCommon'
  - 'RP2_Sdk'
  - 'RP1_MgmtPlane'
  - 'RP1_DataPlane'
  - 'Gallery'
  - 'Intune'
  - 'Common'
  - 'SnippetGenerator'
  - 'docgen'
package_indexing_traversal_stops:
  - 'sdk/'
  - 'src/SDKs/'
  - 'src/SdkCommon/'
  - 'src/AzureStack/'
