omitted_paths:
  - archive/*
  - eng/*
  - tools/*
  - src/*
  - Documentation/*
language: net
root_check_enabled: True
required_readme_sections:
  - "Azure .+ client library for .NET"
  - ^Getting started$
  - ^Key concepts$
  - ^Examples$
  - ^Troubleshooting$
  - ^Next steps$
  - ^Contributing$
known_presence_issues:
  - ['sdk/keyvault','#5499']
  - ['sdk/servicebus','#5499']
  - ['sdk/eventhub','#5499']
  - ['sdk/operationalinsights/Microsoft.Azure.OperationalInsights','#5499']
  - ['sdk/eventgrid/Microsoft.Azure.EventGrid','#5499']
known_content_issues:
  - ['README.md','Root readme']
  - ['sdk/keyvault/Microsoft.Azure.KeyVault/README.md','#5499']
  - ['sdk/servicebus/Microsoft.Azure.ServiceBus/README.md','#5499']
  - ['sdk/eventhub/Microsoft.Azure.EventHubs/README.md','#5499']