supportedEmitters:
  - name: "@azure-typespec/http-client-csharp"
    path: eng/azure-typespec-http-client-csharp-emitter-package.json
  - name: "@azure-typespec/http-client-csharp-mgmt"
    path: eng/azure-typespec-http-client-csharp-mgmt-emitter-package.json
  - name: "@typespec/http-client-csharp"
    path: eng/http-client-csharp-emitter-package.json
  - name: "@azure-tools/typespec-csharp"
    path: eng/legacy-emitter-package.json

