emit:
  - "@azure-typespec/http-client-csharp-mgmt"
options:
  "@azure-typespec/http-client-csharp-mgmt":
    package-name: "Azure.Generator.MgmtTypeSpec"
    namespace: "{package-name}.Tests"
    enable-wire-path-attribute: true
