extends: "{spec-dir}/tspconfig.yaml"
parameters:
  service-dir:
    default: transcription
emit:
  - "@typespec/http-client-csharp"
options:
  "@typespec/http-client-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/Azure.AI.Speech.Transcription"
    package-name: Azure.AI.Speech.Transcription
    unreferenced-types-handling: keepAll
    disable-xml-docs: true
    save-inputs: true
